### ISSUE TITLE
Remove Field Manual

### ISSUE THREAD

**Issue by Shoruto** [PHYNIX-Private-Server/Bug-Reports-#22]
Confirmed works

Tested in East Saru, page 1 for mandies.  Allowed me to purchase after my 6 kills a rr and shell.

![Sporky_2020 03 20_130337](https://user-images.githubusercontent.com/46944745/77187928-9a5d9e80-6aab-11ea-93d7-c8a3ac1b3744.png)
![Uploading Sporky_2020.03.20_1
![Sporky_2020 03 20_130401](https://user-images.githubusercontent.com/46944745/77187933-9c276200-6aab-11ea-94de-62b620d51b3a.png)
![Sporky_2020 03 20_130403](https://user-images.githubusercontent.com/46944745/77187935-9cbff880-6aab-11ea-96b6-30329ae410dd.png)

30354.png…]()

**Comment by ekstaco** [comment]
done
