### ISSUE TITLE
Minor Bug - 7 Dots after Treasure Casket received item

### ISSUE THREAD

**Issue by Shoruto** [PHYNIX-Private-Server/Bug-Reports-#38]
After receiving the item when it shows in your chat box, 7 dots appear each on a separate line.

![Gorgo_2020 03 29_091455](https://user-images.githubusercontent.com/46944745/77850187-c0b3c600-719e-11ea-9a08-3508586f59ec.png)

**Comment by ekstaco** [comment]
Temp item or was it a normal Item?

**Comment by Shoruto** [comment]
silent oil so normal

**Comment by ekstaco** [comment]
attempted to recreate: 
temp item ether, no issue
unable to recreate - I blame bill gates.

**Comment by ekstaco** [comment]
caskets removed
