### ISSUE TITLE
Windurst mission 1-3 

### ISSUE THREAD

**Issue by Arklus** [PHYNIX-Private-Server/Bug-Reports-#7]
No dialogue when handing in offerings .

**Comment by ekstaco** [comment]
if (player:getCurrentMission(WINDURST) == dsp.mission.id.windurst.THE_PRICE_OF_PEACE) then
        if (player:hasKeyItem(dsp.ki.DRINK_OFFERINGS)) then
            -- We have the offerings
            player:startEvent(49);
        else
            if (player:getCharVar("ghoo_talk") == 1) then
                -- npc: You want your offering back?
                player:startEvent(50);
            elseif (player:getCharVar("ghoo_talk") == 2) then
                -- npc: You'll have to crawl back to treasure chamber, etc
                player:startEvent(51);
            else
                -- We don't have the offerings yet or anymore
                player:startEvent(52);
            end
        end
    else
        player:startEvent(52);
    end

**Comment by ekstaco** [comment]
if (player:getCurrentMission(WINDURST) == dsp.mission.id.windurst.THE_PRICE_OF_PEACE) then
        if (player:hasKeyItem(dsp.ki.FOOD_OFFERINGS)) then
            -- We have the offerings
            player:startEvent(45);
        else
            if (player:getCharVar("laa_talk") == 1) then
                -- npc: You want your offering back?
                player:startEvent(46);
            elseif (player:getCharVar("laa_talk") == 2) then
                -- npc: You'll have to crawl back to treasure chamber, etc
                player:startEvent(47);
            else
                -- We don't have the offerings yet or anymore
                player:startEvent(48);
            end
        end
    else
        player:startEvent(48);
    end

**Comment by ekstaco** [comment]
working as intended
